sonar.projectKey=ITPM-Find-My-Hall
sonar.projectName=ITPM-Find My Hall
sonar.projectVersion=1.0
sonar.sources=.
sonar.java.binaries=.
sonar.host.url=http://localhost:9000
sonar.token=sqp_68b4b15fc8f2ae627a49c32611f37bb22b0294ce